DELETE http://localhost:3001/api/persons/2

###
POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "Leprecon73",
    "number": "123-456789000"
}

###
GET http://localhost:3001/